#!/usr/bin/env bash

lgreen_setup-local-bin() {
    if [ -d "$HOME/local/bin" ]; then
        export PATH="$HOME/local/bin":$PATH
    fi
}

lgreen_setup-linuxbrew() {
    if [ -f "/home/linuxbrew/.linuxbrew/bin/brew" ]; then
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        export PATH="/home/linuxbrew/.linuxbrew/bin":$PATH
    fi
}

lgreen_setup-perl() {
    if [ -d "$HOME/perl5/lib/perl5" ]; then
        eval "$(perl -I"$HOME/perl5/lib/perl5" -Mlocal::lib="$HOME/perl5")"
    fi
}

lgreen_setup-umask-for-wsl() {
    if [[ "$(< /proc/version)" = *microsoft* ]]; then
        # Note: WSL does not currently apply umask properly.
        if [ "$(umask)" = "0000" ]; then
            umask 022
        fi
    fi
}

lgreen_setup-display-for-wsl() {
    if [[ "$(< /proc/version)" = *icrosoft* ]]; then
        DISPLAY=$(grep nameserver /etc/resolv.conf | awk '{print $2; exit;}'):0.0
        export DISPLAY
    fi
}

lgreen_setup-fix-wsl2-interop() {
    # Issue: https://github.com/microsoft/WSL/issues/5065
    if [[ "$(< /proc/version)" = *microsoft* ]]; then
        for i in $(pstree -np -s $$ | grep -o -E '[0-9]+'); do
            if [[ -e "/run/WSL/${i}_interop" ]]; then
                export WSL_INTEROP=/run/WSL/${i}_interop
            fi
        done
    fi
}

lgreen_setup-add-windows-path-to-wsl() {
    if [[ "$(< /proc/version)" = *microsoft* ]]; then
        if [ -n "${WSLPATH}" ]; then
            export PATH="$PATH:$WSLPATH"
        fi
    fi
}

lgreen_setup-xdg-config() {
    if [ -z "${XDG_RUNTIME_DIR}" ]; then
         XDG_RUNTIME_DIR=/run/user/$(id -ru)
         export XDG_RUNTIME_DIR
    fi
}

lgreen_setup-package-config() {
    if [ -d "/usr/share/pkgconfig" ]; then
        export PKG_CONFIG_PATH="/usr/share/pkgconfig:$PKG_CONFIG_PATH"
    fi
}

lgreen_setup-package-config
lgreen_setup-umask-for-wsl
lgreen_setup-display-for-wsl
lgreen_setup-fix-wsl2-interop
lgreen_setup-add-windows-path-to-wsl
lgreen_setup-linuxbrew
lgreen_setup-local-bin
lgreen_setup-perl

# TODO: Consider if the below is needed at all for Centos7.  It causes issues on WSL Ubuntu,
# hence commenting it out for now.
# lgreen_setup-xdg-config
