#!/usr/bin/env bash

# Gnu-time
export PATH="/usr/local/opt/gnu-time/libexec/gnubin:$PATH:/Users/lgreen/Library/Python/3.7/bin"

# Homebrew
export PATH="/Users/lgreen/homebrew/bin:$PATH"

updatedb() {
    sudo /usr/libexec/locate.updatedb
}

flushDns() {
    sudo killall -HUP mDNSResponder
}

restartAudio() {
    sudo killall coreaudiod
}
