#!/usr/bin/env bash

# MacPorts
# Note: not using MacPorts any longer due to it
# being to intrusive to company machine.
# export PATH="/opt/local/bin:$PATH"

# Homebrew
# Note: using Homebrew very carefully e.g.
# only installing very popular and useful utilities
# and not installing anything that requests elevated
# permissions.
export PATH=~/.brew/bin:$PATH

# Set locale
export LC_ALL=en_US.UTF-8

# Editor
export ALTERNATE_EDITOR=""
export EDITOR="emacsclient -t -a -c"            # $EDITOR opens in terminal
export VISUAL="emacsclient -c -a emacs"         # $VISUAL opens in GUI mode
