#+TITLE: Dotfiles

Contains config files and setup scripts for 3 platforms:
1. macOS
2. Windows
3. Linux

* Usage
This README provides steps to setup various applications and their associated configurations (the configurations are my own personal ones). To install and setup a specific application simply search this document based on the application name, and one will then get results filtered to the application e.g. if one searches for =Tmux=, then one will find the following: how to install it; how to install the =Tmux Plugin Manager=; how to symlink the config file;

* Install apps
** Install package manager
*** Install =Homebrew= :Linux:macOS:
#+begin_src sh
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#+end_src
*** Install =Scoop= :Windows:
#+begin_src ps
Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
#+end_src
** Install packages
*** Install packages using =Homebrew= :Linux:macOS:
**** Create =Brewfile=
***** Add common =Posix= packages
#+begin_src sh
cat << EOF > ./Brewfile
tap "homebrew/bundle"
tap "homebrew/core"

brew "bat"
brew "coreutils"
brew "dust"
brew "fd"
brew "htop"
brew "ispell"
brew "keychain"
brew "neofetch"
brew "neovim"
brew "pstree"
brew "ripgrep"
brew "stow"
brew "tldr"
brew "tree"
brew "tmux"
brew "isync"
brew "mu"
brew "sword"
EOF
#+end_src

***** Add =Posix= development packages
#+begin_src sh
cat << EOF >> ./Brewfile

brew "automake"
brew "clang-format"
brew "cmake"
brew "editorconfig"
brew "python"
brew "direnv"
brew "freetds@0.91", link: true
brew "git"
brew "openjdk"
brew "gradle"
brew "jenv"
brew "jq"
brew "llvm"
brew "ninja"
brew "node"
brew "pyenv"
brew "pyenv-virtualenv"
brew "ruby-build"
brew "rbenv"
brew "rbtools"
brew "ruby"
brew "unixodbc"
EOF
#+end_src

***** Add =Linux= development packages
#+begin_src sh
cat << EOF >> ./Brewfile

brew "bash"
brew "fswatch"
brew "gcc"
brew "perl"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
brew "zsh"
EOF
#+end_src

***** Add =macOS= specific packages
#+begin_src
cat << EOF >> ./Brewfile

#tap "d12frosted/emacs-plus"                    -- not sure which one is better
#brew "d12frosted/emacs-plus/emacs-plus@27"     -- not sure which one is better

tap "daviderestivo/emacs-head"
brew "daviderestivo/emacs-head/emacs-head@28", args: ["with-cocoa", "with-modern-icon-elrumo2"]
EOF
#+end_src

***** Add =macOS= development packages
#+begin_src sh
cat << EOF >> ./Brewfile

tap "cartr/qt4"
brew "cartr/qt4/pyqt@4"
cask "docker"
EOF
#+end_src

***** Add =macOS= casks
#+begin_src sh
cat << EOF >> ./Brewfile

tap "homebrew/cask"
tap "homebrew/cask-fonts"

#cask "amethyst"    -- unused - replaced by Hammerspoon
#cask "caffeine"    -- unused - replaced by Hammerspoon
#cask "keycastr"    -- unused - replaced by Hammerspoon

cask "appcleaner"
cask "alfred"
cask "cursorcerer"
cask "divvy"                        # TODO Replace Divvy with Hammerspoon
cask "lincastor"                    # TODO Replace Lincastor with Hammerspoon
cask "font-iosevka-nerd-font"
cask "hammerspoon"
cask "iterm2"
cask "shortcutdetective"
cask "basictex"
EOF
#+end_src

**** Use =Brewfile=
#+begin_src sh
brew bundle
#+end_src
*** Install packages using =Scoop= :Windows:
#+begin_src ps
#-----------------------
# Command-line utilities
#-----------------------
scoop install ack
scoop install aria2
scoop install bat
scoop install clink
scoop install coreutils
scoop install curl
scoop install dust
scoop install fd
scoop install findutils
scoop install fzf
scoop install neofetch
scoop install ripgrep
scoop install tldr
scoop install wget

#----------
# Terminals
#----------
scoop install alacritty

#--------
# Editors
#--------
scoop install emacs
scoop install neovim
scoop install vscode

#------
# Fonts
#------
scoop install Hack
scoop install iosevka

#-----------------
# System utilities
#-----------------
scoop install 7zip
scoop install everything
scoop install openssh
scoop install processhacker
scoop install rapidee
scoop install sudo
scoop install sysinternals
scoop install windirstat

#------------------
# Desktop utilities
#------------------
scoop install autohotkey
scoop install carnac
scoop install keypirinha
scoop install powertoys
scoop install sumatrapdf
scoop install vlc
scoop install wox

#------------
# Development
#------------
scoop install cmake
scoop install git
scoop install nodejs
scoop install openjdk
scoop install perl
scoop install python
scoop install springboot
scoop install vcredist2015
#+end_src

** Install from sources
Sometime we have to install from sources on systems that have dated packages and that =Homebrew= does not run on e.g. =CentOS 7=.
*** Installing =Tmux=
**** Install =Tmux= from =Github=
#+BEGIN_SRC sh
git clone https://github.com/tmux/tmux.git
cd tmux
sh autogen.sh
./configure
make && sudo make install
#+END_SRC
**** Install =Tmux= from =Sourceforge=
#+BEGIN_SRC sh
# Install libevent
LIBEVENT_VERSION="2.0.21-stable"
[ -d ~/packages ] || mkdir ~/packages; pushd ~/packages;
wget https://github.com/downloads/libevent/libevent/libevent-$LIBEVENT_VERSION.tar.gz
tar zxvf libevent-$LIBEVENT_VERSION.tar.gz
cd libevent-$LIBEVENT_VERSION
./configure --prefix=/usr/local
make && sudo make install

# Install Tmux
TMUX_VERSION="3.2"
[ -d ~/packages ] || mkdir ~/packages; pushd ~/packages;
wget http://downloads.sourceforge.net/tmux/tmux-$TMUX_VERSION.tar.gz
tar zxvf tmux-$TMUX_VERSION.tar.gz
cd tmux-$TMUX_VERSION
LDFLAGS="-L/usr/local/lib -Wl,-rpath=/usr/local/lib" ./configure --prefix=/usr/local
make && sudo make install
#+END_SRC
*** Installing =ZSH=
#+BEGIN_SRC sh
ZSH_SRC_LINK="https://sourceforge.net/projects/zsh/files/latest/download"
ZSH_SRC_FILE="zsh.tar.xz"

TMP_DIR=$(mktemp -d) && cd $TMP_DIR
curl -Lo "$ZSH_SRC_FILE" "$ZSH_SRC_LINK"
tar xJvf "$ZSH_SRC_FILE" --strip-components 1
./configure --prefix="/usr/local" \
    CPPFLAGS="-I/usr/local/include" \
    LDFLAGS="-L/usr/local/lib"
make -j && sudo make install
#+END_SRC

*** Installing =fzf= from =Github=
#+BEGIN_SRC sh
git clone --depth 1 https://github.com/junegunn/fzf.git
cd fzf
./install
#+END_SRC
*** Installing =fd= using =Cargo=
#+BEGIN_SRC sh
cargo install fd-find
ln -s ~/.cargo/bin ~/bin # optional if the cargo bin is default in PATH
#+END_SRC
*** Installing =bat= using =Cargo=
#+BEGIN_SRC sh
cargo install bat
ln -s ~/.cargo/bin ~/bin # optional if the cargo bin is default in PATH
#+END_SRC
** Install python apps with =pip=
#+begin_src
pip install dploy
#+end_src
* Install app specific plugin managers
** Install =Tmux Plugin Manager=
#+begin_src sh
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
#+end_src

** Install =Zinit= a =Zsh= plugin manager :automated:
The ~./shell/dot-zshrc~ checks if =Zinit= is installed and prompts user to run below steps:
#+begin_src sh
mkdir ~/.zinit
git clone https://github.com/zdharma/zinit.git ~/.zinit/bin
#+end_src
** Install =Sword='s =installmgr=
#+begin_src sh
export SWORD_PATH=~/.sword
mkdir -p $SWORD_PATH/mods.d

echo yes |installmgr -init               # create a basic user config file
echo yes |installmgr -sc                 # sync config with list of known remote repos
echo yes |installmgr -r CrossWire        # refresh remote source
echo yes |installmgr -ri CrossWire KJV   # install module from remote source
installmgr -l                            # list installed modules

#Test
diatheke -b KJV -k Jn 3:16
#+end_src

* Install app integrations
Some of these are auto-installed, by apps themselves according to their config, but the below are not.
** Shell integrations
*** Install =Fzf=
#+begin_src sh
$(brew --prefix)/opt/fzf/install
#+end_src

** Editor integrations
*** =Chemacs 2=
Note: Using =Chemacs= means one has to run modified instructions for installing an Emacs distribution e.g. =Doom= or =Spacemacs=
The install instructions for =Chemacs 2= state to clone the repository, but we add it as a git submodule into the ~dot-emacs.d~ directory, ready for usage with =stow=.

*** Install =Doom Emacs=
Note: If using =Chemacs= then the below is slightly different from the instructions from the web-site i.e. the target directory should not be ~.emacs.d~ since this is where =Chemacs= will be installed to.
#+begin_src sh
git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.doom
~/.emacs.doom/bin/doom install
#+end_src

*** Install =Latex tools=
Note: The system should be installed via a package manager e.g. ~brew install basictex~, which provides the ~tlmgr~, which should then be used:
#+begin_src sh
sudo tlmgr update --self && \
    sudo tlmgr install \
    # for svg images
    dvisvgm \
    # for png images
    dvipng \
    # fonts
    collection-fontsrecommended \
    # source code highlighting
    minted
#+end_src

I am not sure if the below is needed?
#+begin_src sh
sudo tlmgr install wrapfig marvosym wasy wasysym
#+end_src

* Symlink dotfiles
Initially I had some hand written scripts for doing the symlinking, but am now using =GNU Stow= since it is a more standardized approach.

** Symlink dotfiles using =Gnu Stow= :Linux:macOS:
*** Stow =Posix= configs
#+begin_src sh
stow shell git git_my git_work tmux vim nvim emacs
#+end_src

*** Stow =macOS= config
#+begin_src sh
stow shell_osx git_osx alacritty_osx hammerspoon
#+end_src

*** Stow =Linux= config
#+begin_src sh
stow shell_linux git_linux alacritty_linux
#+end_src

** Symlink dotfiles using =Dploy= :Windows:
Unfortunately there is no =Gnu Stow= for =Windows=, but the =dploy= python package comes to the rescue.
#+begin_src ps
# Pre-requisates
# - Install Dploy: ~pip instal dploy~
# - Run the below in an Admin session e.g. ~sudo powershell~

#-------------------
# Windows only stuff
#-------------------
dploy stow ./alacritty_win $home
dploy link ./autohotkey/dot-autohotkey $home/.autohotkey
dploy stow ./Keypirinha $home
dploy stow ./WindowsPowerShell $home
dploy stow ./WindowsTerminal $home

#-------------
# Vim + Neovim
#-------------
dploy link ./vim/dot-vimrc $home/_vimrc
dploy link ./vim/dot-gvimrc $home/_gvimrc
dploy stow ./nvim/.config/nvim $home/appdata/local/nvim

#-------------
# Emacs
#-------------
dploy link ./emacs/dot-emacs-profile $home/.emacs-profile
dploy link ./emacs/dot-emacs-profiles.el $home/.emacs-profiles.el
dploy link ./emacs/dot-emacs.default $home/.emacs.default
dploy link ./emacs/dot-doom.d $home/.doom.d

#-------------
# Git
#-------------
dploy link ./git/dot-gitignore $home/.gitignore
dploy link ./git/dot-common.gitconfig $home/.common.gitconfig
dploy link ./git_my/dot-my.gitconfig $home/.my.gitconfig
dploy link ./git_win/dot-gitconfig $home/.gitconfig
#+end_src

* Testing using Docker
** Pull docker base image
#+begin_src sh
docker pull archlinux/archlinux:base-devel
#+end_src
** Build docker image
#+begin_src sh
docker build --ssh default -t lambertgreen/dotfiles .
#+end_src
** Run docker container
#+begin_src sh
docker run -it lambertgreen/dotfiles
#+end_src

* TODOs
** DONE Test reproducibility by using =Docker=
CLOSED: [2021-06-02 Wed 16:05]
** DONE Fix first start of =Nvim= to no show errors
CLOSED: [2021-06-02 Wed 21:33]
** TODO Replace individual per package calls with combined single line installs
For example ~scoop p1 p2 p3~
** TODO Consider adding =Chemacs2= and =Doom= as sub-modules
So that simply doing ~stow emacs~ get things all done, or provide shorter setup blocks.
