#!/bin/sh

# Setup FZF to use fd
export FZF_DEFAULT_COMMAND='fd --type f'

export P4CONFIG=.p4config

# Aliases
gw () {
    ./gradlew "$@"
}

SetupDevEnvJava () {
    if [ -d "$HOME/.jenv/bin" ]; then
        export PATH="$HOME/.jenv/bin:$PATH"
        eval "$(jenv init -)"
    fi
}

SetupDevEnvNode () {
    export NVM_DIR="$HOME/.nvm"
    [ -s "/usr/local/opt/nvm/nvm.sh" ] && s "/usr/local/opt/nvm/nvm.sh"
    [ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"
}

SetupDevEnvRust () {
    export PATH="$PATH:$HOME/.cargo/bin"
}

SetupDevEnvRuby () {
    export PATH="$PATH:$HOME/.rvm/bin"
    # Source Ruby Version Manager
    [ -s "$HOME/.rvm/scripts/rvm" ] && . "$HOME/.rvm/scripts/rvm"
}

SetupDevEnvGo () {
    export GOPATH="${HOME}/.go"
    export GOROOT="$(brew --prefix golang)/libexec"
    export PATH="$PATH:${GOPATH}/bin:${GOROOT}/bin"
    test -d "${GOPATH}" || mkdir "${GOPATH}"
    test -d "${GOPATH}/src/github.com" || mkdir -p "${GOPATH}/src/github.com"
}

