#!/usr/bin/env bash

lgreen_osx_flush_dns() {
    echo "Sudo needed - run the below:"
    echo sudo killall -HUP mDNSResponder
}

# Aliases
alias updatedb="/usr/libexec/locate.updatedb"
alias flush-dns="killall -HUP mDNSResponder"
alias restart-audio="killall coreaudiod"
alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
