#!/usr/bin/env bash

# Set uname
[ -v $UNAME ];  export UNAME=$(uname -s)

# Setup FZF to use fd
export FZF_DEFAULT_COMMAND='fd --type f --hidden --no-ignore-vcs'

# Perforce config
export P4CONFIG=.p4config

# Setup LS COLOR
if hash vivid 2> /dev/null; then
    LS_COLORS="$(vivid generate snazzy)"
    export LS_COLORS
    if [ "$UNAME" = "Darwin" ]; then
        alias ls="gls --color"
        alias ll="gls -lh --color"
        alias la="gls -lAh --color"
    fi
else
    true
fi

#----------
# Aliases
#----------
alias vim=nvim
alias vi=nvim

# Git aliases
alias ga='git add'
alias gs='git status'
alias gc='git commit'
alias gl='git log'
alias gp='git pull'
alias gd='git diff'

#----------
# Functions
#----------
gw () {
    ./gradlew "$@"
}

SetupDevEnvJava () {
    if [ -d "$HOME/.jenv/bin" ]; then
        export PATH="$HOME/.jenv/bin:$PATH"
        eval "$(jenv init -)"
    fi
}

SetupDevEnvNode () {
    export NVM_DIR="$HOME/.nvm"
    [ -s "/usr/local/opt/nvm/nvm.sh" ] && s "/usr/local/opt/nvm/nvm.sh"
    [ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"
}

SetupDevEnvRust () {
    export PATH="$PATH:$HOME/.cargo/bin"
}

SetupDevEnvRuby () {
    export PATH="$PATH:$HOME/.rvm/bin"
    # Source Ruby Version Manager
    [ -s "$HOME/.rvm/scripts/rvm" ] && . "$HOME/.rvm/scripts/rvm"
}

SetupDevEnvGo () {
    export GOPATH="${HOME}/.go"
    export GOROOT="$(brew --prefix golang)/libexec"
    export PATH="$PATH:${GOPATH}/bin:${GOROOT}/bin"
    test -d "${GOPATH}" || mkdir "${GOPATH}"
    test -d "${GOPATH}/src/github.com" || mkdir -p "${GOPATH}/src/github.com"
}

TimeShell() {
  shell=${1-$SHELL}
  for _ in $(seq 1 10); do time $shell -i -c exit; done
}
