#!/usr/bin/env bash

# Aliases
alias updatedb="/usr/libexec/locate.updatedb"
alias flushDns="killall -HUP mDNSResponder"
alias restartAudio="killall coreaudiod"
alias lldb="/usr/local/Cellar/llvm/9.0.1/bin/lldb"
