#!/usr/bin/env bash

lgreen_setup_msys_nativesymlinks() {
	export MSYS=winsymlinks:nativestrict
}

lgreen_setup_mintty_256color() {
    if [[ "$(uname_cached)" == *"_NT"* ]]; then
        export TERM=xterm-256color
    fi
}

lgreen_setup_oh-my-posh() {
    if [ "$(command -v oh-my-posh)" ]; then
		# FIXME: should we be relying on projects being pulled down into pub folder?
		eval "$(oh-my-posh init bash --config ~/dev/pub/oh-my-posh/themes/amro.omp.json)"
	fi
}

lgreen_setup_msys_nativesymlinks
lgreen_setup_mintty_256color
lgreen_setup_oh-my-posh
