#!/usr/bin/env bash

# MacPorts
# Note: not using MacPorts any longer due to it
# being to intrusive to company machine.
# export PATH="/opt/local/bin:$PATH"

# Homebrew
#
# Note: using Homebrew very carefully e.g.
# only installing very popular and useful utilities
# and not installing anything that requests elevated
# permissions.
#
# Note: I have tried for a second time to use brew installed
# into a home local directory. This works fine for just
# applications, but it's a problem when one needs to
# install libraries e.g. trying to build something
# that needs an include file for a library installed
# via brew.

# export PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:$PATH
lgreen_setup_homebrew() {
    # TODO Get woman in Emacs working by setting MANPATH by calling 'manpath' executable
    # TODO Consider not calling 'brew shellenv' since it will set MANPATH, but that does not
    # set a comprehensive value... really for macOS the 'manpath' value should be used.
    if [  -f "/usr/local/bin/brew" ]; then
        eval "$(/usr/local/bin/brew shellenv)"
    fi

    # Brew is installed in a different location on mac aarm64
    if [  -f "/opt/homebrew/bin/brew" ]; then
        eval "$(/opt/homebrew/bin/brew shellenv)"
    fi
}

lgreen_setup_homebrew
