#!/usr/bin/env bash

lgreen_setup_msys_nativesymlinks() {
	export MSYS=winsymlinks:nativestrict
}

lgreen_setup_mintty_256color() {
    if [ -z "$UNAME" ]; then export UNAME=$(uname -s); fi
    if [[ "$UNAME" == *"_NT"* ]]; then
        export TERM=xterm-256color
    fi
}

lgreen_setup_oh-my-posh() {
	eval "$(oh-my-posh init bash --config ~/dev/pub/oh-my-posh/themes/amro.omp.json)"
}

lgreen_setup_msys_nativesymlinks
lgreen_setup_mintty_256color
lgreen_setup_oh-my-posh
