#!/usr/bin/env bash

lgreen_add_scoop_bins_to_path() {
    export PATH="$HOME/scoop/shims:$PATH"
}

lgreen_add_emacs_local_build_to_path() {
    export PATH="$HOME/.local/emacs/bin:$PATH"
}

lgreen_add_scoop_bins_to_path
lgreen_add_emacs_local_build_to_path
