#!/usr/bin/env bash

lgreen_setup_msys_path() {
	# Add Git to front of path
	export PATH="/c/Program Files/Git/cmd:$PATH"

	export PATH="$PATH:$HOME/scoop/apps/python/current/Scripts"
	export PATH="$PATH:$HOME/scoop/apps/openjdk/current/bin"
	export PATH="$PATH:$HOME/scoop/apps/nodejs-lts/current"
	export PATH="$PATH:$HOME/scoop/apps/nodejs-lts/current/bin"
}

lgreen_setup_msys_nativesymlinks() {
	export MSYS=winsymlinks:nativestrict
}

lgreen_setup_mintty_256color() {
    if [ -z "$UNAME" ]; then export UNAME=$(uname -s); fi
    if [[ "$UNAME" == *"_NT"* ]]; then
        export TERM=xterm-256color
    fi
}

lgreen_setup_msys_path
lgreen_setup_msys_nativesymlinks
lgreen_setup_mintty_256color
